### ISSUE TITLE
Invalid format error with ReferenceEntityAttributeApi

### ISSUE THREAD

**Issue by nicolasfl** [akeneo/api-php-client-ee#96]
Hi, 

I'm trying to add an attribute on a reference entity with the API but I've got a really weird error : 
The attribute has an invalid format.  

I thought it was a mistake on my side but then I tried to add the same format as in your documentation here : 
https://api.akeneo.com/php-client/resources.html#reference-entity-attribute
`$client->getReferenceEntityAttributeApi()->upsert('brand', 'description', [
        'code' => 'description',
        'labels' => [
            'en_US' => 'Description'
        ],
        'type' => 'text',
        'localizable' => true,
        'scopable' => true,
        'is_required_for_completeness' => false
    ]);`       

I tried to remove every lines except type and code and I still get the error. 
What did I missed ? 

Thank for your help in advance.

**Comment by LevFlavien** [comment]
Hi @nicolasfl 

Thank you for reporting an issue.
Since the EE package is getting deprecated and this issue is 2 years old, I'm closing this.
If this is still relevant to you, feel free to reopen an issue on the appropriate repository https://github.com/akeneo/api-php-client

Regards,

Akeneo development team
